import type { Passenger, LoungePost } from "./types";

const iso = (daysAgo: number) =>
  new Date(Date.now() - daysAgo * 86_400_000).toISOString();

export const PASSENGERS: Passenger[] = [
  {
    id: "p_margaret",
    name: "Margaret Oyelaran",
    age: 74,
    pronouns: "she/her",
    city: "Ann Arbor, MI",
    seed: 11,
    gate: "A4",
    status: "ON_TIME",
    runway: "My mother made it to 97 and was rude the whole time. I'm pacing myself.",
    mobility: "CANE",
    intents: ["ROMANCE", "MEALS", "PHYSICAL"],
    bio: "Retired labour and delivery nurse, forty-one years. I have caught roughly nine thousand babies and I have never once cried at a wedding. I gave up on being mysterious around 1988. Ask me anything, I'll tell you, and then I'd like you to do the same.",
    itinerary: [
      "See the northern lights",
      "Eat oysters somewhere they were pulled that morning",
      "Learn to swim properly, not the flailing I do now",
      "Go a whole week without checking the weather",
    ],
    goodDays: "Mornings. By four o'clock I'm honest but I'm not charming.",
    greenFlags: ["Reads actual books", "Can be quiet in a car", "Knows how to apologise"],
    lastWords:
      "I'm not fragile and I'm not a project. If you're looking for someone to take care of, there are apps for that and this isn't one.",
    preflight: {
      lastTested: iso(40),
      disclosures: ["HSV-2, well managed, happy to talk about it"],
      immunocompromised: false,
      vaccinesCurrent: true,
      note: "I spent four decades telling people to get tested. It would be embarrassing not to.",
    },
    verified: true,
    joinedAt: iso(56),
  },
  {
    id: "p_desmond",
    name: "Desmond Achebe",
    age: 68,
    pronouns: "he/him",
    city: "Ypsilanti, MI",
    seed: 3,
    gate: "B12",
    status: "BOARDING",
    runway: "Pancreatic. They said a year in March and I've decided to be difficult about it.",
    mobility: "WALKING",
    intents: ["ROMANCE", "COMPANY", "WITNESS"],
    bio: "I drove a city bus for thirty years, route 12, and I could tell you the life story of everyone who got on before 7am. Now I have a lot of time and a firm diagnosis, which turns out to be a strange kind of freedom. I've stopped doing things I don't want to do. It's been the best six months of my life, which is an insane sentence to type.",
    itinerary: [
      "See the northern lights",
      "Ride the whole of route 12 one more time, in the back, as a passenger",
      "Teach someone to make my mother's jollof properly",
      "Say the thing to my brother",
    ],
    goodDays: "Tuesdays and Thursdays — chemo's Monday, so I'm useless Mon–Wed morning.",
    greenFlags: ["Laughs at the wrong moment", "Drives", "Not scared of hospitals"],
    lastWords:
      "You don't have to be brave around me. Everyone's being so brave and it's exhausting. You can just be sad about it for a minute.",
    preflight: {
      lastTested: iso(90),
      disclosures: [],
      immunocompromised: true,
      vaccinesCurrent: true,
      note: "Chemo means my immune system is a joke. If you have a sniffle, we do the phone instead. No hard feelings, ever.",
    },
    verified: true,
    joinedAt: iso(38),
  },
  {
    id: "p_ruth",
    name: "Ruth Kaminski",
    age: 81,
    pronouns: "she/her",
    city: "Detroit, MI",
    seed: 22,
    gate: "A19",
    status: "ON_TIME",
    runway: "Ask my cardiologist, she's more pessimistic than I am.",
    mobility: "WHEELCHAIR",
    intents: ["COMPANY", "MEALS", "CORRESPONDENCE"],
    bio: "Widowed eleven years. Sol was a good man and a terrible cook and I have finally stopped setting two places. I play bridge competitively, which is a sentence people find funny until they lose to me. I want someone to argue with about films. I don't need a husband, I had a very good one.",
    itinerary: [
      "Eat oysters somewhere they were pulled that morning",
      "See every film nominated for Best Picture, in a cinema, like God intended",
      "Get back to Kraków",
      "Beat someone at bridge who thought they'd let me win",
    ],
    goodDays: "Any day with a matinee in it.",
    greenFlags: ["Opinions about films", "Punctual", "Doesn't talk during the movie"],
    lastWords:
      "The chair is not the interesting thing about me and I will know within four minutes whether you've worked that out.",
    preflight: {
      lastTested: null,
      disclosures: [],
      immunocompromised: false,
      vaccinesCurrent: true,
      note: "I'll get tested when there's a reason to. Tell me if there's a reason to.",
    },
    verified: true,
    joinedAt: iso(120),
  },
  {
    id: "p_hal",
    name: "Hal Brennan",
    age: 71,
    pronouns: "he/him",
    city: "Toledo, OH",
    seed: 7,
    gate: "C2",
    status: "DELAYED",
    runway: "COPD. It's a slow one. I'll be here annoying people for a while yet.",
    mobility: "CANE",
    intents: ["COMPANY", "MEALS", "ROMANCE"],
    bio: "Forty years a machinist, twelve years sober, one very good dog. I talk too much and I'm working on it, though everyone who says that is lying and I might be too. I can fix almost anything with a motor in it. I cannot fix a relationship, which I learned the expensive way, twice.",
    itinerary: [
      "Drive the whole Lake Michigan loop with no schedule",
      "Learn to swim properly, not the flailing I do now",
      "Get my daughter to answer the phone",
      "Eat at a restaurant with cloth napkins without feeling like a fraud",
    ],
    goodDays: "Cool dry days. Humidity puts me on the couch.",
    greenFlags: ["Owns tools and knows what they're for", "Sober-friendly", "Good with the dog"],
    lastWords:
      "I've got oxygen at night and it makes a noise. I'd rather you knew that now than found out at the worst possible moment.",
    preflight: {
      lastTested: iso(200),
      disclosures: [],
      immunocompromised: false,
      vaccinesCurrent: true,
      note: "Overdue, honestly. Booking it this week now that I've typed it out.",
    },
    verified: false,
    joinedAt: iso(21),
  },
  {
    id: "p_bernice",
    name: "Bernice Toth",
    age: 66,
    pronouns: "she/her",
    city: "Ann Arbor, MI",
    seed: 15,
    gate: "A7",
    status: "FINAL_CALL",
    runway: "Hospice at home. They stopped giving me numbers, which is its own kind of number.",
    mobility: "HOMEBOUND",
    intents: ["COMPANY", "CORRESPONDENCE", "WITNESS"],
    bio: "I was a high school choir director for thirty-two years and I can still hear when you're flat. I am not looking for a boyfriend, I'm looking for a person. Someone to come sit in the yellow chair and tell me about their week and their boring problems, which are the best kind of problem to hear about when you've run out of your own.",
    itinerary: [
      "Hear live music one more time, even badly played",
      "Say the thing to my brother",
      "Have someone read me the end of a book I won't finish",
      "Sit outside at night when it's warm",
    ],
    goodDays: "Late morning, after the meds settle. About two good hours.",
    greenFlags: ["Comfortable with silence", "Will let me be the one asking questions", "Brings nothing"],
    lastWords:
      "I know what this is. You don't have to manage my expectations, I've done that myself. Just don't disappear without telling me — that's the only rule.",
    preflight: {
      lastTested: null,
      disclosures: [],
      immunocompromised: true,
      vaccinesCurrent: true,
      note: "Please don't visit if you're unwell. It's not caution at this point, it's just courtesy.",
    },
    verified: true,
    joinedAt: iso(12),
  },
  {
    id: "p_arthur",
    name: "Arthur Lindqvist",
    age: 79,
    pronouns: "he/him",
    city: "Ann Arbor, MI",
    seed: 30,
    gate: "B3",
    status: "STANDBY",
    runway: "Kidney list, eighteen months in. Some days that's hope and some days it's just a list.",
    mobility: "WALKING",
    intents: ["ROMANCE", "COMPANY", "PHYSICAL"],
    bio: "Retired architect. I designed four libraries and one truly ugly parking structure that I'd like to formally apologise for. Dialysis three days a week, which gives you a lot of time to read and a real appreciation for the other four. Divorced a long time ago, amicably, and we still send each other cards.",
    itinerary: [
      "See the northern lights",
      "Get back to Kraków",
      "Sleep next to somebody again",
      "Swim in the ocean once more",
    ],
    goodDays: "Tuesday, Thursday, Saturday. Dialysis owns the others.",
    greenFlags: ["Curious", "Cooks", "Not frightened by the word 'dying'"],
    lastWords:
      "Standby is the hardest status to date on. I might get a call at 3am and vanish for a month, or I might never get the call. You should know that's the deal.",
    preflight: {
      lastTested: iso(25),
      disclosures: [],
      immunocompromised: true,
      vaccinesCurrent: true,
      note: "Tested constantly, they check everything before a transplant. I'll show you the printout, it's genuinely the most documented body in Michigan.",
    },
    verified: true,
    joinedAt: iso(75),
  },
  {
    id: "p_yolanda",
    name: "Yolanda Reyes-Park",
    age: 63,
    pronouns: "she/her",
    city: "Detroit, MI",
    seed: 44,
    gate: "C11",
    status: "BOARDING",
    runway: "Stage four, in the lungs now. Eighteen months if I'm lucky and I've been lucky before.",
    mobility: "WALKING",
    intents: ["ROMANCE", "PHYSICAL", "MEALS"],
    bio: "I ran a restaurant for twenty years and I have opinions about your salt. Two grown kids who call too much, which I complain about and love. I want to be somebody's girlfriend again. Not a patient, not a cause, not the brave lady from the fundraiser. A girlfriend. Someone who gets annoyed at me about the thermostat.",
    itinerary: [
      "Eat oysters somewhere they were pulled that morning",
      "Dance in public without being self-conscious",
      "Teach someone to make my mother's jollof properly",
      "Swim in the ocean once more",
      "Have a genuinely stupid argument about the thermostat",
    ],
    goodDays: "First three weeks of the cycle. Fourth week I'm a bear, and I warn people.",
    greenFlags: ["Eats everything", "Flirts back", "Doesn't say 'fighting' or 'journey'"],
    lastWords:
      "If the first thing you say to me is that I'm inspiring, I'm going to pass. I'm not inspiring. I'm hungry and I'm bored.",
    preflight: {
      lastTested: iso(15),
      disclosures: [],
      immunocompromised: true,
      vaccinesCurrent: true,
      note: "Immunocompromised from treatment. I still want a sex life. Those two facts are both allowed to be true — we just talk about it first like adults.",
    },
    verified: true,
    joinedAt: iso(30),
  },
  {
    id: "p_walter",
    name: "Walter Nkemdirim",
    age: 86,
    pronouns: "he/him",
    city: "Ypsilanti, MI",
    seed: 5,
    gate: "A1",
    status: "ON_TIME",
    runway: "Eighty-six and the doctors keep looking surprised. I've stopped making plans past Christmas but I keep making it to Christmas.",
    mobility: "CANE",
    intents: ["COMPANY", "MEALS", "CORRESPONDENCE"],
    bio: "I came here in 1962 with a suitcase and a scholarship. Taught chemistry to teenagers who did not want chemistry. Widowed six years — Adaeze was the whole thing, honestly, and I'm not looking to replace her. But the house is quiet in a way I don't like and I've been told that admitting that is the first step.",
    itinerary: [
      "Have Sunday lunch with someone every week",
      "Hear live music one more time, even badly played",
      "Ride the whole of route 12 one more time, in the back, as a passenger",
      "Write down the family history before it goes with me",
    ],
    goodDays: "Every day, slowly. I've got nowhere to be.",
    greenFlags: ["Patient", "Interested in old stories", "Won't rush me"],
    lastWords:
      "I'm quite slow now, in the walking and in the talking. If that's going to irritate you it's better we find out on the first cup of tea.",
    preflight: {
      lastTested: null,
      disclosures: [],
      immunocompromised: false,
      vaccinesCurrent: true,
      note: "Not a concern for me at present, but I'd tell you if it were.",
    },
    verified: true,
    joinedAt: iso(90),
  },
  {
    id: "p_juno",
    name: "Juno Vasquez",
    age: 59,
    pronouns: "they/them",
    city: "Ann Arbor, MI",
    seed: 19,
    gate: "B8",
    status: "DELAYED",
    runway: "ALS, slow variant. Two years since diagnosis. It takes something new every few months.",
    mobility: "WHEELCHAIR",
    intents: ["ROMANCE", "COMPANY", "WITNESS"],
    bio: "Former union organiser, current pain in everyone's neck. I type with my eyes now, which is either science fiction or a party trick depending on the day. My speech is going but my sense of humour is fully intact and honestly meaner than ever. I'm looking for someone who can handle a conversation that takes a while.",
    itinerary: [
      "Sit outside at night when it's warm",
      "Get arrested one last time for something worthwhile",
      "Have someone read me the end of a book I won't finish",
      "Hear live music one more time, even badly played",
    ],
    goodDays: "Afternoons. Mornings are all logistics and other people's hands.",
    greenFlags: ["Patient with the typing", "Political", "Doesn't finish my sentences"],
    lastWords:
      "It takes me a minute to answer. Sit in the minute with me instead of filling it — that's the whole test, and most people fail it.",
    preflight: {
      lastTested: iso(60),
      disclosures: [],
      immunocompromised: false,
      vaccinesCurrent: true,
      note: "Respiratory stuff is what gets people like me. Please be honest if you're sick.",
    },
    verified: true,
    joinedAt: iso(45),
  },
  {
    id: "p_estelle",
    name: "Estelle Byrd",
    age: 77,
    pronouns: "she/her",
    city: "Toledo, OH",
    seed: 26,
    gate: "C6",
    status: "ON_TIME",
    runway: "Nothing's wrong with me. I just noticed I'm running out of people my own age.",
    mobility: "WALKING",
    intents: ["ROMANCE", "PHYSICAL", "MEALS"],
    bio: "Three husbands. Loved two of them. I sing in a bar on Thursdays for free drinks and the attention, and I'm honest about which one I'm there for. I don't do slow burns anymore — at my age a slow burn is just a fire you didn't live to see.",
    itinerary: [
      "Dance in public without being self-conscious",
      "Drive the whole Lake Michigan loop with no schedule",
      "Hear live music one more time, even badly played",
      "Have a wildly inappropriate romance and tell nobody",
    ],
    goodDays: "Nights. I'm nocturnal and unrepentant.",
    greenFlags: ["Can dance or will try", "Buys the first round", "Not a bit shy"],
    lastWords:
      "Everybody on here is very serious and I understand why, but I'd like to have some fun before the end and I don't think that's shallow.",
    preflight: {
      lastTested: iso(20),
      disclosures: [],
      immunocompromised: false,
      vaccinesCurrent: true,
      note: "I get tested every three months and I'll ask you when you last did. This is not the app where we skip that conversation — the risk that goes away with age is pregnancy, and that's the only one.",
    },
    verified: true,
    joinedAt: iso(18),
  },
  {
    id: "p_terrence",
    name: "Terrence Mbeki",
    age: 70,
    pronouns: "he/him",
    city: "Detroit, MI",
    seed: 9,
    gate: "A22",
    status: "BOARDING",
    runway: "Heart failure, the long goodbye kind. A year or two, they think, but they've been wrong twice.",
    mobility: "CANE",
    intents: ["COMPANY", "CORRESPONDENCE", "WITNESS"],
    bio: "Postal carrier, thirty-four years, same route. I know which houses have the good dogs. I'm gay and I came out at sixty-one, which means I got about nine good years of being myself and I'm greedy for more. Never had the big love. Would like one, briefly, if that's available.",
    itinerary: [
      "Have the big love, even a short one",
      "Sleep next to somebody again",
      "Go to Pride once without feeling like a tourist",
      "Sit outside at night when it's warm",
    ],
    goodDays: "Mornings, before the swelling starts.",
    greenFlags: ["Out or working on it", "Writes back", "Kind to waiters"],
    lastWords:
      "I spent sixty years being careful. I'm done being careful about who I am. I'm still careful about the other thing, obviously — see the panel.",
    preflight: {
      lastTested: iso(30),
      disclosures: ["HIV negative, on PrEP"],
      immunocompromised: false,
      vaccinesCurrent: true,
      note: "On PrEP, tested quarterly. Came up in the eighties. We do not skip this conversation, ever, and anyone who wants to skip it is telling you something.",
    },
    verified: true,
    joinedAt: iso(60),
  },
  {
    id: "p_ingrid",
    name: "Ingrid Sørensen",
    age: 84,
    pronouns: "she/her",
    city: "Ann Arbor, MI",
    seed: 33,
    gate: "B15",
    status: "DELAYED",
    runway: "Dementia, early. I'm writing this down while it's still mine to write.",
    mobility: "WALKING",
    intents: ["COMPANY", "MEALS", "WITNESS"],
    bio: "I was a translator — Danish, German, English. Words were the whole job and now they come and go. My daughter helped me put this up. I know what's ahead. I would like to have a nice time first, with someone who will not be frightened when I ask them the same question twice.",
    itinerary: [
      "Write down the family history before it goes with me",
      "Have Sunday lunch with someone every week",
      "Go a whole week without checking the weather",
      "Hear live music one more time, even badly played",
    ],
    goodDays: "Mornings are clearest. Evenings I'm not always sure of myself.",
    greenFlags: ["Repeats things kindly", "Knows my daughter's number", "Doesn't test me"],
    lastWords:
      "There will be a point where I don't know you. I'd still like to have known you before that. My daughter Kirsten is my ground crew and she reads these with me.",
    preflight: {
      lastTested: null,
      disclosures: ["Early Alzheimer's — my daughter helps me use this app"],
      immunocompromised: false,
      vaccinesCurrent: true,
      note: "Kirsten checks in on anyone I meet. That's not distrust, it's just how we're doing this.",
    },
    verified: true,
    joinedAt: iso(9),
  },
  {
    id: "p_ray",
    name: "Ray Kowalczyk",
    age: 69,
    pronouns: "he/him",
    city: "Ypsilanti, MI",
    seed: 41,
    gate: "C18",
    status: "STANDBY",
    runway: "Waiting on a trial. If I'm in, maybe years. If I'm out, considerably fewer.",
    mobility: "WALKING",
    intents: ["MEALS", "COMPANY", "ROMANCE"],
    bio: "Line cook, then sous, then a bad back. I cook for six people minimum because I don't know how to do less. Divorced, three kids who are fine, one who isn't. I check my email forty times a day for a letter that decides how long I get, which is a stupid way to live and I can't stop.",
    itinerary: [
      "Teach someone to make my mother's jollof properly",
      "Eat oysters somewhere they were pulled that morning",
      "Have Sunday lunch with someone every week",
      "Get my daughter to answer the phone",
    ],
    goodDays: "All of them, structurally. It's the waiting that's the problem, not the body.",
    greenFlags: ["Hungry", "Will sit in a kitchen and talk", "Distracting"],
    lastWords:
      "I'd like to think about something other than the trial for one evening. That's the actual ask. Feed me a distraction and I'll feed you properly.",
    preflight: {
      lastTested: iso(50),
      disclosures: [],
      immunocompromised: false,
      vaccinesCurrent: true,
      note: "Screened top to bottom for the trial. They test for things I'd never heard of.",
    },
    verified: false,
    joinedAt: iso(14),
  },
  {
    id: "p_priya",
    name: "Priya Raghunathan",
    age: 61,
    pronouns: "she/her",
    city: "Detroit, MI",
    seed: 28,
    gate: "A9",
    status: "FINAL_CALL",
    runway: "Weeks. I'm in the hospice on Woodward and the view is genuinely lovely.",
    mobility: "INPATIENT",
    intents: ["CORRESPONDENCE", "COMPANY", "WITNESS"],
    bio: "Mathematician. Forty years of number theory, one moderately famous proof, no regrets about the hours. I have a room with two chairs and a window and more time than company. I'd like to talk to someone new before I stop being able to. Nothing heavy. Tell me about your commute.",
    itinerary: [
      "Have someone read me the end of a book I won't finish",
      "Hear live music one more time, even badly played",
      "Meet one new person a week until I can't",
      "Sit outside at night when it's warm",
    ],
    goodDays: "10am to about 2pm. After that I'm mostly asleep and not good company.",
    greenFlags: ["Not squeamish", "Talks about ordinary things", "Short visits, kept"],
    lastWords:
      "Please don't come once and then feel too guilty to come again. Once is fine. Just say it's once.",
    preflight: {
      lastTested: null,
      disclosures: [],
      immunocompromised: true,
      vaccinesCurrent: true,
      note: "The ward has rules and they're good rules. Masks if you've got anything at all.",
    },
    verified: true,
    joinedAt: iso(6),
  },
  {
    id: "p_gordon",
    name: "Gordon Fairweather",
    age: 73,
    pronouns: "he/him",
    city: "Toledo, OH",
    seed: 17,
    gate: "B21",
    status: "ON_TIME",
    runway: "Healthy as a horse, which is starting to feel like a social problem.",
    mobility: "WALKING",
    intents: ["ROMANCE", "COMPANY", "PHYSICAL"],
    bio: "Retired veterinarian. I put a lot of animals to sleep gently and it taught me more about dying than anything since. Widowed two years. I signed up here because a friend on this app told me the conversations were better, and she was right, and then she died, and I stayed.",
    itinerary: [
      "Drive the whole Lake Michigan loop with no schedule",
      "Swim in the ocean once more",
      "Learn to swim properly, not the flailing I do now",
      "Sleep next to somebody again",
    ],
    goodDays: "Anytime. The dog gets walked at six and eight regardless of who's here.",
    greenFlags: ["Steady", "Good in a crisis", "Has met death before"],
    lastWords:
      "I'm the healthy one on here and I'm aware that's a complicated thing to be. I'm not here to collect sad stories. I'm here because you lot are the only people who talk straight.",
    preflight: {
      lastTested: iso(35),
      disclosures: [],
      immunocompromised: false,
      vaccinesCurrent: true,
      note: "Recently tested. If I'm going to be around immunocompromised people I keep my shots current — that's on me, not them.",
    },
    verified: true,
    joinedAt: iso(48),
  },
  {
    id: "p_alma",
    name: "Alma Whitefeather",
    age: 68,
    pronouns: "she/her",
    city: "Ann Arbor, MI",
    seed: 37,
    gate: "C4",
    status: "BOARDING",
    runway: "Ovarian, recurrent. Third round. I'm told this is the one that finishes it.",
    mobility: "CANE",
    intents: ["COMPANY", "PHYSICAL", "ROMANCE", "WITNESS"],
    bio: "Potter, forty years. My hands still work, which is the only medical fact I actually care about. I've buried a husband and a son and I'm not going to pretend that's not part of the package. But I laugh a lot, more than most people expect, and I'd like to do that next to somebody.",
    itinerary: [
      "Dance in public without being self-conscious",
      "See the northern lights",
      "Sit outside at night when it's warm",
      "Have a genuinely stupid argument about the thermostat",
      "Teach one more person to throw a pot",
    ],
    goodDays: "Weekends. Treatment's Wednesday and it takes three days off the top.",
    greenFlags: ["Uses their hands for something", "Has lost somebody too", "Unafraid of a cemetery"],
    lastWords:
      "I've been on the other side of this — I was the healthy one twice. I know exactly what I'm asking of somebody and I'll never pretend it's nothing.",
    preflight: {
      lastTested: iso(45),
      disclosures: [],
      immunocompromised: true,
      vaccinesCurrent: true,
      note: "Neutropenic some weeks. I'll tell you which weeks. On those we do the phone and it's genuinely fine.",
    },
    verified: true,
    joinedAt: iso(27),
  },
];

export const LOUNGE_SEED: LoungePost[] = [
  { id: "l1", room: "jokes", author: "p_desmond", body: "Doctor asked if I'd considered getting my affairs in order. Told him I'd considered having one first. He did not laugh. You lot will.", at: iso(2), hearts: 31 },
  { id: "l2", room: "jokes", author: "p_estelle", body: "My grandson called this app 'morbid'. I said darling, morbid is a nursing home with a jigsaw. This is a departure lounge with a bar.", at: iso(1), hearts: 44 },
  { id: "l3", room: "scan", author: "p_ray", body: "Day two of three. I have cleaned the entire kitchen including behind the fridge. Behind the fridge, everyone. Someone talk to me about literally anything else.", at: iso(1), hearts: 18 },
  { id: "l4", room: "scan", author: "p_alma", body: "Ray — the trick is to book something for the day after the results that you'd be annoyed to miss. Gives the fear a job to do.", at: iso(1), hearts: 22 },
  { id: "l5", room: "widowed", author: "p_walter", body: "Six years. Still set the kettle for two some mornings. I've stopped being embarrassed about it and started thinking of it as a small hello.", at: iso(4), hearts: 67 },
  { id: "l6", room: "widowed", author: "p_ruth", body: "Walter, I did two plates for four years. Someone told me it wasn't healthy. Someone was not the one eating alone.", at: iso(3), hearts: 51 },
  { id: "l7", room: "caregivers", author: "p_ingrid", body: "My daughter is on here reading over my shoulder. Kirsten says hello and also that I should mention I am a handful. I am not.", at: iso(5), hearts: 29 },
  { id: "l8", room: "caregivers", author: "p_gordon", body: "For the carers: you're allowed to want an evening where nobody needs anything from you. That doesn't make you a bad one. It makes you a person who's been on shift for two years.", at: iso(2), hearts: 40 },
  { id: "l9", room: "jokes", author: "p_priya", body: "Told the chaplain I'd worked out the maths on the afterlife and it didn't converge. He said that was the point. Genuinely the best answer anyone's given me in here.", at: iso(3), hearts: 38 },
  { id: "l10", room: "widowed", author: "p_terrence", body: "Odd one for this room: I'm widowed from a life, not a person. Sixty years in the closet. Grieving the man I didn't get to be, and it turns out that grief works the same way.", at: iso(6), hearts: 72 },
];
